language: java

jdk:
 - openjdk7

#env: MAVEN_OPTS="-Dio.netty.leakDetectionLevel=paranoid"

#script: mvn -Dtest=net.tomp2p.p2p.TestAnnounce test && exit 1

install: mvn install -DskipTests=true -B

before_script: 
 - chmod a+x /home/travis/build/tomp2p-nat/src/test/resources/nat-net.sh/nat-net.sh
 - ls -la
 - sudo sh -c 'echo "travis ALL=(ALL) NOPASSWD: /home/travis/build/tomp2p-nat/src/test/resources/nat-net.sh/nat-net.sh" >> /etc/sudoers'
 - sudo sh -c 'echo "travis ALL=(ALL) NOPASSWD: /sbin/ip" >> /etc/sudoers'
 - sudo cat /etc/sudoers

script: mvn test -Dmaven.javadoc.skip=true
