language: java

jdk:
 - openjdk7

#env: MAVEN_OPTS="-Dio.netty.leakDetectionLevel=paranoid"

#script: mvn -Dtest=net.tomp2p.p2p.TestAnnounce test && exit 1

install: mvn install -DskipTests=true

before_script: 
 - sudo sh -c 'echo "$USER ALL=(ALL) NOPASSWD: ${pwd}/tomp2p-nat/src/test/resources/nat-net.sh/nat-net.sh" >> /etc/sudoers'
 - sudo sh -c 'echo "$USER ALL=(ALL) NOPASSWD: /sbin/ip" >> /etc/sudoers'
 - sudo cat /etc/sudoers
 - chmod a+x {pwd}/tomp2p-nat/src/test/resources/nat-net.sh/nat-net.sh
 - ls -la

script: mvn test -Dmaven.javadoc.skip=true
